dependencies {
    //Authentication-management-API
    implementation project(':authentication-management-server:authentication-management-service-api')
    //User-Service-API
    implementation project(":user-server:user-service-api")
    //Chat-Service-API
    implementation project(":chat-server:chat-service-api")
    // Jwt
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
}

test {
    enabled = false
}
