apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: api-gateway-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.100"
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-server
  ports:
    - protocol: TCP
      port: 5424
      targetPort: 6000
