dependencies {
	// Common module
    implementation project(':common-module')
    // Spring Cloud Gateway
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    // Redis Reactive
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    // Kubernetes Discovery
    implementation 'org.springframework.cloud:spring-cloud-kubernetes-discovery'
    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
}
