rootProject.name = 'flowofessence'

include('api-gateway-server')

include('authentication-management-server:authentication-management-domain')
include('authentication-management-server:authentication-management-infra')
include('authentication-management-server:authentication-management-service-api')
include('authentication-management-server:authentication-management-service-contracts')

include('common-module')
