apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-discovery-client
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: api-gateway-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: authentication-management-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: chat-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: api-service-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: content-delivery-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: game-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: matchmaking-server
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: logging-monitoring-server

roleRef:
  kind: ClusterRole
  name: service-discovery-client
  apiGroup: rbac.authorization.k8s.io
