dependencies {
    //Common module
    api project(':common-module')
    //QueryDSL
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
}

clean {
    delete file('src/main/generated')
}

test {
    enabled = false
}

bootJar { enabled = false }
jar { enabled = true }
